### ISSUE TITLE
Provide a page property injector

### ISSUE THREAD

**Issue by royteeuwen** [wcm-io/io.wcm.sling.models#1]
A common use case that I see coming back a lot of times is accessing page properties in a sling model. I would propose to create a custom Injector for this.

I'd like to propose to create a @PageProperty annotation. Is this something that you would be open to accept as contribution? I don't see any custom annotations besides @AemObject, so I'm not sure if you would want to expand on the custom annotations

**Comment by stefanseifert** [comment]
are you thinking about something like this? https://adobe-consulting-services.github.io/acs-aem-commons/features/sling-model-injectors/hierarchical-page-property/

(optional) inheritance should probably taken into account as well.

it would be a nice addition i think - not everyone wants to pull in full ACS AEM Commons just for such a selector.

**Comment by stefanseifert** [comment]
available now in ACS commons: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3159

closing this - if there is interest in having it standalone as well, we can reopen it
