### ISSUE TITLE
Page adaptTo is broken

### ISSUE THREAD

**Issue by YahorPronski** [wcm-io/io.wcm.sling.models#2]
I noticed that io.wcm.sling.models breaks adaptTo method of com.day.cq.core.impl.Page

**Comment by stefanseifert** [comment]
can you give more details in which way it breaks? e.g. code example, stacktrace or similar? to which class to you adapt?

**Comment by YahorPronski** [comment]
> can you give more details in which way it breaks? e.g. code example, stacktrace or similar? to which class to you adapt?

Here is pseudo code:

import com.day.cq.wcm.api.Page;

page.adaptTo(MyCustomClass.class) -> wrong adaptation 

page.adaptTo(Resource.class).adaptTo(MyCustomClass.class) -> works fine

Disabling io.wcm.sling.models bundle makes the first option work

**Comment by YahorPronski** [comment]
import com.day.cq.wcm.api.Page;
import org.apache.sling.api.resource.Resource;

import static org.apache.jackrabbit.JcrConstants.JCR_PRIMARYTYPE;

public abstract class BasePageModel {
    private String pageId;

    protected final Page page;
    protected final Resource contentResource;

    protected BasePageModel(Page page) {
        this.page = page;
        contentResource = page.getContentResource();
    }

    protected BasePageModel(Resource resource) {
        if (resource != null && "cq:PageContent".equals(resource.getValueMap().get(JCR_PRIMARYTYPE, String.class))) {
            page = resource.getParent().adaptTo(Page.class);
            contentResource = resource;
        } else {
            page = resource.adaptTo(Page.class);
            contentResource = page.getContentResource();
        }
    }

    protected void init() {
        pageId = "some id";
    }
}

**Comment by stefanseifert** [comment]
this is not a bug in `io.wcm.sling.models` but an ambiguity in your code. here is the reason for the behavior:
* you are using constructor injection for the constructors in ArticlePageModel without actually defining an injector, so sling models checks for all available injectors (this is bad practice, as it also comes with an performance overhead)
* without `io.wcm.sling.models` present, there is not injector who cares about "Page" object, so as last resort it injects the adaptable itself
* but with `io.wcm.sling.models` present, there is an injector present, and it injects the current page

the solution is to always specify the injection you expect:
* in your case, change the constructor to `public ArticlePageModel(@Self Page page)` to get the expected result
* alternatively, to get the current page you could use `public ArticlePageModel(@AemObject Page page)`

same applies if you are using field injections.

**Comment by YahorPronski** [comment]
Thanks for your answer very much.
I wasn't sure about the correctness of this code, but thanks for your explanation, now I understand why it depends on io.wcm.slings.model bundle.
We will refactor our code, hope it helps.
The issue can be closed.
